### ISSUE TITLE
unable to update the content

### ISSUE THREAD

**Issue by alberanid** [imdbpy/website#11]
I've committed to this repository some hours ago (the announcement of the new release), but the website is not updated, yet.

Is something broken with the lektor-bot automation? (I'm not sure to have full access to Travis).

Thanks.

**Comment by uyar** [comment]
Couldn't figure this out. It's probably due to changes in Travis. I'll try to convert it to GitHub Actions. Manual deployment didn't work either, I'm getting authentication failure (because of 2FA maybe?) Can you try it? Run:

lektor build -f cssbuild
lektor deploy ghpages

**Comment by uyar** [comment]
It looks like switching to github actions fixed it.

**Comment by alberanid** [comment]
that's great, thanks!
