### ISSUE TITLE
Lektor seems to be broken due to dependency problem

### ISSUE THREAD

**Issue by alberanid** [imdbpy/website#14]
The `werkzeug.posixemulation` module was removed from werkzeug 2, but Lektor still needs it.

I think the best solution is to just wait a fix for https://github.com/lektor/lektor/issues/909

If no solution is provided in a few weeks, we can just add `Werkzeug<=1` to requirements.txt

See the error at: https://github.com/imdbpy/website/runs/2700823615?check_suite_focus=true

**Comment by uyar** [comment]
It makes sense to pin the proper versions. There is a newer lektor version as well, I'll check to see whether it would be OK to update.
