### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by alberanid** [imdbpy/website#8]
It seems that the build is broken: https://travis-ci.org/imdbpy/website/builds/570160745?utm_medium=notification&utm_source=email

Looks like that, locally, running `npm install` fixes the problem. Not sure how this should be done on Travis.

**Comment by uyar** [comment]
I see. It's a bug in my cssbuild plugin. The check whether to run npm install is incorrect. I'll fix it later today. In the meantime, if your local build is successful, you can deploy using "lektor deploy ghpages" if you like.
